name: Sysdig Image Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SYSDIG_SECURE_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
  SYSDIG_SECURE_URL: https://app.au1.sysdig.com

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t voting-app ./vote
          docker build -t worker ./worker
          docker build -t result ./result

      - name: Run Sysdig Scan via Docker image (scan subcommand)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SYSDIG_SECURE_TOKEN=$SYSDIG_SECURE_TOKEN \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              scan \
              --apiurl $SYSDIG_SECURE_URL \
              docker://voting-app

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SYSDIG_SECURE_TOKEN=$SYSDIG_SECURE_TOKEN \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              scan \
              --apiurl $SYSDIG_SECURE_URL \
              docker://worker

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SYSDIG_SECURE_TOKEN=$SYSDIG_SECURE_TOKEN \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              scan \
              --apiurl $SYSDIG_SECURE_URL \
              docker://result

