name: Sysdig Docker Image Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
  SYS_DIG_SECURE_URL: https://app.au1.sysdig.com

jobs:
  image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t voting-app ./vote
          docker build -t worker ./worker
          docker build -t result ./result

      - name: Scan voting-app
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
            scan docker://voting-app \
              --apiurl "$SYS_DIG_SECURE_URL" \
              --token "$SECURE_API_TOKEN"

      - name: Scan worker
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
            scan docker://worker \
              --apiurl "$SYS_DIG_SECURE_URL" \
              --token "$SECURE_API_TOKEN"

      - name: Scan result
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
            scan docker://result \
              --apiurl "$SYS_DIG_SECURE_URL" \
              --token "$SECURE_API_TOKEN"

