name: Sysdig Image Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  image-scan:
    runs-on: ubuntu-latest

    env:
      SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
      SYS_DIG_SECURE_URL: https://app.au1.sysdig.com

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3

      - name: 🧱 Build Docker images
        run: |
          docker build -t voting-app ./vote
          docker build -t worker ./worker
          docker build -t result ./result

      - name: 🔍 Scan voting-app with Sysdig
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v "${{ github.workspace }}/scan-logs:/home/nonroot/scan-logs" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }} \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl $SYS_DIG_SECURE_URL \
              --loglevel debug \
              --skiptlsverify \
              docker://voting-app

      - name: 🔍 Scan worker with Sysdig
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v "${{ github.workspace }}/scan-logs:/home/nonroot/scan-logs" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }} \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl $SYS_DIG_SECURE_URL \
              --loglevel debug \
              --skiptlsverify \
              docker://worker

      - name: 🔍 Scan result with Sysdig
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v "${{ github.workspace }}/scan-logs:/home/nonroot/scan-logs" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }} \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl $SYS_DIG_SECURE_URL \
              --loglevel debug \
              --skiptlsverify \
              docker://result

