name: Sysdig Image Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t voting-app ./vote
          docker build -t worker ./worker
          docker build -t result ./result

      - name: Run Sysdig CLI Scanner (with CLI flags)
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
              --apiurl https://app.au1.sysdig.com \
              --client-token $SECURE_API_TOKEN \
              docker://voting-app

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
              --apiurl https://app.au1.sysdig.com \
              --client-token $SECURE_API_TOKEN \
              docker://worker

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            quay.io/sysdig/sysdig-cli-scanner:latest \
              --apiurl https://app.au1.sysdig.com \
              --client-token $SECURE_API_TOKEN \
              docker://result

